Repository balenalabs/balena-sound, pull requests merged in 2020-04, with the labels that each got.

#132 Added CLIENT_ONLY to multi room audio
  README.md
  airplay/start.sh
  bluetooth-audio/start.sh
  docker-compose.yml
  fleet-supervisor/server.js
  fleet-supervisor/start.sh
  snapcast-server/start.sh
  spotify/start.sh
Labels: enhancement, multi room

#140 Change device name variable
  README.md
  airplay/start.sh
  bluetooth-audio/start.sh
  spotify/start.sh
Labels: airplay, bluetooth, enhancement, spotify

#143 Update var picture
  images/device-name-config.png
Labels: enhancement

#152 add -M to amixer to fix volume mapping issues #117
  bluetooth-audio/bluetooth-udev
  bluetooth-audio/start.sh
Labels: bug

#147 Support old variables
  bluetooth-audio/start.sh
Labels: enhancement

#156 Change to balena project to enable builds in CI
  repo.yml
Labels: enhancement

#157 Add more DACs
  DAC_configuration.md
Labels: DAC config, enhancement

#154 WIP: Add Troubleshooting
  TROUBLESHOOTING.md
Labels: enhancement

#173 Add images in preparation for Landr update.
  images/hardware.jpeg
  images/sdcard.gif
  images/sound.png
Labels: docs

#175 Add sample "deploy to balena" button
  README.md
Labels: docs, enhancement

#178 Versionbot folder
  .versionbot/.gitkeep
Labels: docs, enhancement
